# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme: blowfish
baseURL: "https://rin.systems/"
defaultContentLanguage: en
enableRobotsTXT: true
paginate: 20
summaryLength: 100
buildDrafts: false
buildFuture: false
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
outputs:
  home:
    - HTML
    - RSS
    - JSON
taxonomies:
  series: "series"
